Move start session logic
Mickalu/redux-saga-exercise pull request #2
Opened 2022-11-23 13:35 UTC by Mickalu

https://trello.com/c/9a1KIEQ7/6-move-start-session-logic

Déplacer et adapter la logique de l'action startSession de src/actions/index.js dans un fichier de saga dans src/sagas/index

2022-11-23 13:48 UTC, lapwil requested changes

2022-11-23 13:48 UTC, lapwil commented on src/sagas/index.js
> +    yield spawn(sessionSaga)
alors spawn est bien et pas bien à la fois, tu as regardé un peu ce que ça faisait ?

une chose aussi qu'on préfère faire, c'est mettre dans le rootSaga le dispatcher de nos sagas.

Donc récupérer les effects de tes autres fichiers pour les lister ici

2022-11-23 15:53 UTC, Mickalu commented on src/sagas/index.js
> +    yield spawn(sessionSaga)
Le spawn permet de séparer les différents saga afin que si il y en a un qui crash les autres ne soit pas impacté je crois. 

Donc dans les fichiers enfants on fait `
export default function* rootSaga(){
    yield takeEvery(START_SESSION, fetchStartSession)
    yield takeEvery(RECEIVE_SESSION, fetchReceiveSession)
};`

Et dans les parents on a juste à récupérer le root saga de tous les fichiers enfants pour faire un 
`
export default function* rootSaga() {
    yield all([
        rootSaga(),
    ])
};
` 
?

2022-11-24 10:09 UTC, lapwil requested changes

2022-11-24 10:09 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +      this.props.startSession;
ben tu le call pas là du coup

2022-11-24 10:43 UTC, Mickalu commented on src/containers/TinderContainer.jsx
> +      this.props.startSession;
J'avais oublié le takeEvery du coup je voyais ma fonction se lancer, je me suis fais avoir

2022-11-24 16:20 UTC, lapwil requested changes

2022-11-24 16:20 UTC, lapwil commented on src/sagas/index.js
> +    yield takeEvery(START_SESSION, rootSagaSession.fetchStartSession)
un autre effect est plus intéressant ici

2022-11-24 16:20 UTC, lapwil commented on src/sagas/sagaSession.js
> +import { RECEIVE_SESSION } from "../actions";
newline avant tes imports

2022-11-24 16:20 UTC, lapwil commented on src/sagas/sagaSession.js
> +    try{
espace avant la bracket

2022-11-24 16:20 UTC, lapwil commented on src/sagas/sagaSession.js
> +        yield put({type: RECEIVE_SESSION, session: session} );
espace chelou après ton object
ajoutes en avant type et après session

2022-11-24 16:20 UTC, lapwil commented on src/store/configureStore.dev.js
> +import createSagaMiddleware, { runSaga } from "redux-saga";
pourquoi l'import de runSaga ici ?

2022-11-24 16:20 UTC, lapwil commented on src/actions/index.js
> +import { actionChannel } from 'redux-saga/effects'
semicolon manquant

2022-11-24 16:20 UTC, lapwil commented on src/components/App.jsx
> +import store from '../store'
semicolon manquant

2022-11-24 16:20 UTC, lapwil commented on src/index.jsx
> +import store from './store'
semicolon manquant

2022-11-24 16:20 UTC, lapwil commented on src/store/configureStore.dev.js
> +    runSaga: sagaMiddleWare.run
virgule manquante ici

2022-11-25 16:42 UTC, lapwil approved these changes

2022-11-25 17:00 UTC, lapwil approved these changes

2022-11-28 09:15 UTC, merged