9 create run tests
Mickalu/redux-saga-exercise pull request #4
Opened 2022-11-28 11:36 UTC by Mickalu

https://trello.com/c/lWqqdl0O/

Tests fetchBeers saga when beers already fetching and when not 
Two test need to be creating

2022-11-30 09:34 UTC, lapwil requested changes
conflict

2022-11-30 13:10 UTC, lapwil requested changes
retire ton dernier commit et merge master dans la branche plutôt

2022-11-30 15:17 UTC, lapwil requested changes

2022-11-30 15:17 UTC, lapwil commented on coverage/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
tu peux retirer les fichiers de coverage du git

2022-11-30 15:17 UTC, lapwil commented on src/sagas/fetchBeersSaga.js
> +
newline en trop

2022-11-30 15:17 UTC, lapwil commented on src/sagas/index.spec.js
> +    }}
quitte à faire du multilign, fais le vraiment sur tout l'objet et sur session, sinon tu peux les faire en one-lign ceux là (manque un espace ligne 29)

2022-11-30 15:17 UTC, lapwil commented on src/sagas/index.spec.js
> +    expect(putReceiveBeers.value).to.be.deep.equal(put(receiveBeers(beers)));
dans un test, il faut prévoir le moins d'expect possible, si ce n'est pas des tests de rendering.

Ce test devrait donc être splitté par étapes, à toi de voir comment le faire

2022-11-30 15:17 UTC, lapwil commented on src/sagas/index.spec.js
> +
newline en trop

2022-11-30 15:17 UTC, lapwil commented on src/sagas/index.spec.js
> +
newline en trop

2022-11-30 15:17 UTC, lapwil commented on src/sagas/index.spec.js
>    it('should NOT fetch beers if it is already fetching beers', () => {
tu ne montres pas que ça ne fetch pas de beers du coup

2022-12-01 08:22 UTC, lapwil requested changes

2022-12-01 08:22 UTC, lapwil commented on src/sagas/index.spec.js
> +it('#Saga: startSession', () => {
comme dit dans notre point, utilises test plutot que l'alias quand on a pas de describe

2022-12-01 08:22 UTC, lapwil commented on src/sagas/index.spec.js
> +  it("should call api session", () => {
on disait aussi d'éviter de nester les tests

2022-12-01 08:22 UTC, lapwil commented on src/sagas/index.spec.js
> +  }
virgule et point virgule manquants

2022-12-01 08:22 UTC, lapwil commented on src/sagas/index.spec.js
> +  })
point virgule et newline

2022-12-01 08:22 UTC, lapwil commented on src/sagas/index.spec.js
> +  })
point virgule

2022-12-01 08:24 UTC, lapwil commented on src/sagas/index.spec.js
>  });
et du coup tu as viré le test qui montre que ça ne fetch pas ?

2022-12-01 14:03 UTC, Mickalu commented on src/sagas/index.spec.js
>  });
Je pensais que puisque l'on a enlever la sécurité avec le return puisque nous avons takeLeading qui protège déjà je pouvais l'enlever

2022-12-01 14:04 UTC, Mickalu commented on src/sagas/index.spec.js
>  });
J'ai du mal comprendre ce que tu voulais dire alors désolé

2022-12-02 13:12 UTC, lapwil requested changes

2022-12-02 13:12 UTC, lapwil commented on src/sagas/index.spec.js
>  });
hum et du coup le test n'est pas encore fait

2022-12-02 13:12 UTC, lapwil commented on src/sagas/index.spec.js
> +import { expect } from 'chai'
tu as maintenant jest non ? as-tu besoin de ce expect ?

2022-12-02 13:12 UTC, lapwil commented on src/sagas/index.spec.js
> +import fetchBeersSaga from "./fetchBeersSaga";
à ranger comme il faut

components

actions 

api

selectors

2022-12-02 14:02 UTC, Mickalu commented on src/sagas/index.spec.js
> +import { expect } from 'chai'
Non je n'ai pas jest sur cette branch, je l'ai mise que sur la branche 11 pour tout ce qui est test de composants et de container

2022-12-02 15:12 UTC, lapwil approved these changes

2022-12-02 15:15 UTC, merged