11 add like beer saved
Mickalu/redux-saga-exercise pull request #6
Opened 2022-12-01 08:19 UTC by Mickalu

https://trello.com/c/n5fKCXbU/11-add-like-beer-saved

- Add redux saga with likes button 
- create tests for this 
- display all liked beers

2022-12-01 08:49 UTC, lapwil requested changes

2022-12-01 08:49 UTC, lapwil commented on jest.config.js
> +  // ],
faut le prendre ça

2022-12-01 08:49 UTC, lapwil commented on jest.config.js
> +  // ],
aussi en précisant ce qu'il faut

2022-12-01 08:49 UTC, lapwil commented on jest.config.js
> +  setupFilesAfterEnv: ["<rootDir>/jest-setup.js", "./jest-setup.js"],
t'as mis deux fois le même ici

2022-12-01 08:49 UTC, lapwil commented on jest.config.js
> +    "./src/sagas/__tests__/",
utilises rootdir plutot

2022-12-01 08:49 UTC, lapwil commented on jest.config.js
> +  // The glob patterns Jest uses to detect test files
ça aussi faut le mettre

2022-12-01 08:49 UTC, lapwil commented on jest.config.js
> +  // testPathIgnorePatterns: [
idem

2022-12-01 08:49 UTC, lapwil commented on src/__tests__/customeMethodRTL.js
> +const renderCustome = (element, store) => {
pas de e à custom

2022-12-01 08:49 UTC, lapwil commented on src/__tests__/customeMethodRTL.js
> +import React from "react";
les indentations dans ce fichier sont pas bonnes

2022-12-01 08:49 UTC, lapwil commented on src/__tests__/customeMethodRTL.js
> +}
ya une meilleur syntaxe à utiliser

2022-12-01 08:49 UTC, lapwil commented on src/__tests__/customeMethodRTL.js
> +const renderCustome = (element, store) => {
et autre syntaxe à utiliser

2022-12-01 08:49 UTC, lapwil commented on src/__tests__/initValues.js
> +const initListBeers =
revoie l'indentation de ce fichier

2022-12-01 08:49 UTC, lapwil commented on src/actions/index.js
> +  beerId
je viens de voir qu'il y a plusieurs objets qui n'ont pas de virgule à chaque ligne ici

2022-12-01 08:49 UTC, lapwil commented on src/actions/index.js
>  })
il manque aussi quelques point virgules

2022-12-01 08:49 UTC, lapwil commented on src/components/Main.jsx
>  import React from 'react'
manque des points virgules dans ces imports

2022-12-01 08:49 UTC, lapwil commented on src/components/Navigations/Menu.jsx
>  )
point virgule

2022-12-01 08:49 UTC, lapwil commented on src/components/Navigations/Menus/Beersliked.jsx
> +import {v4} from 'uuid';
pas au bon endroit, et des espaces manquants

2022-12-01 08:49 UTC, lapwil commented on src/components/Navigations/Menus/Beersliked.jsx
> +  console.log(props);
ça dégage

2022-12-01 08:49 UTC, lapwil commented on src/components/Navigations/Menus/Beersliked.jsx
> +  mapStateToProps
si on fait du multilign, virgule manquante

2022-12-01 08:49 UTC, lapwil commented on src/components/Navigations/Menus/__tests__/BeersLiked.spec.js
> +import React from "react";
identation à revoir

2022-12-01 08:49 UTC, lapwil commented on src/components/Navigations/Menus/__tests__/BeersLiked.spec.js
> +import { queryAllByTestId, render} from "../../../../__tests__/customeMethodRTL";
range ça de manière logique

2022-12-01 08:49 UTC, lapwil commented on src/components/Navigations/Menus/__tests__/BeersLiked.spec.js
> +});
du coup je disais qu'il faut que tu changes le component appelé ici pour ne pas avoir à donner tout un store différent entre tes tests

2022-12-01 08:49 UTC, lapwil commented on src/config/index.js
> +export const BEER_LIMIT_PER_PAGE = 10
points virgules

2022-12-01 08:49 UTC, lapwil commented on src/containers/BeersLikedContainer.jsx
> +import BeersLiked from '../components/Navigations/Menus/BeersLiked';
newline avant

2022-12-01 08:49 UTC, lapwil commented on src/containers/BeersLikedContainer.jsx
> +}
c'est quoi ce container sans render ?

pourquoi utiliser react-container-component ?

2022-12-01 08:49 UTC, lapwil commented on src/containers/BeersLikedContainer.jsx
> +});
si c'est vide, ça dégage

2022-12-01 08:49 UTC, lapwil commented on src/containers/BeersLikedContainer.jsx
> +}
je viens de voir que c'est dans le projet de base.

c'est plus d'actualité, si tu peux les transformer en container basiques qui extends Component plutôt

2022-12-01 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +    const nextBeerIdx = this.props.currentBeerIndex + 1;
une good practice est de décomposer props en début de fonction

2022-12-01 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +    const beerId = this.props.beer.id;
idem

2022-12-01 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +  likes: state.likes,
faudra penser à les ranger + point virgule manquant

2022-12-01 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +  addLike: (beerId) => dispatch(actions.addLike(beerId)),
faudra penser à les ranger + point virgule manquant

2022-12-01 08:49 UTC, lapwil commented on src/reducers/likesReducer.js
> +import { ADD_BEER_LIKE } from "../actions";
indentation à revoir

2022-12-01 08:49 UTC, lapwil commented on src/sagas/__tests__/addBeerLikeSaga.spec.js
> +import { expect } from "chai";
indentation à revoir

2022-12-01 08:49 UTC, lapwil commented on src/sagas/__tests__/addBeerLikeSaga.spec.js
> +});
faudra le splitté ça

2022-12-01 08:49 UTC, lapwil commented on src/sagas/addBeerLikeSaga.js
> +import { put, select } from "redux-saga/effects";
indentation à revoir

2022-12-01 08:49 UTC, lapwil commented on src/sagas/index.js
>  import { takeLeading, takeEvery } from 'redux-saga/effects';
indentation à revoir

2022-12-01 08:49 UTC, lapwil commented on src/sagas/index.js
> +import addLikesSaga from "./addBeerLikeSaga";
harmonise tes imports

2022-12-01 08:49 UTC, lapwil commented on src/sagas/index.spec.js
> +import { expect } from 'chai'
plus besoin de ça

2022-12-01 08:49 UTC, lapwil commented on src/selectors/index.js
> +export const isFetchingBeers = (state) => (
manque les virgules et points virgule ici

2022-12-01 08:49 UTC, lapwil commented on src/utils/__tests__/renderMethodRTL.js
> +import { screen } from "@testing-library/react";
pourquoi ne pas avoir fait un setup comme je t'ai montré ?

2022-12-01 08:49 UTC, lapwil commented on src/utils/getInfoBeer.js
> +    const result = listBeers.find(beer => beer.id == beerId);
tu peux directement renvoyer le find du coup

et la condition n'est pas correcte

2022-12-01 11:45 UTC, Mickalu commented on src/utils/__tests__/renderMethodRTL.js
> +import { screen } from "@testing-library/react";
C'étais mon prochain commit je voulais résoudre tous les bugs avant de le faire mais du coup je vais le faire là

2022-12-02 15:07 UTC, lapwil requested changes

2022-12-02 15:07 UTC, lapwil commented on src/containers/BeersLikedContainer.jsx
> +        beers={this.props.beers}
utilises la décomposition

2022-12-02 15:07 UTC, lapwil commented on src/containers/BeersLikedContainer.jsx
> +    super(props)
semicolon

2022-12-02 15:07 UTC, lapwil commented on src/containers/Beersliked/Beersliked.jsx
> +import { v4 } from 'uuid';
mal rangé

2022-12-02 15:07 UTC, lapwil commented on src/containers/Beersliked/Beersliked.jsx
> +const BeersLiked = (props) => {
utilises la décomposition pour props

et utilises une autre syntaxe ES6

2022-12-02 15:07 UTC, lapwil commented on src/containers/TinderContainer.jsx
>  class TinderContainer extends Container {
comme pour l'autre component, utilises plutôt React.Component et vire ce Container

pars du principe que si c'est dans le diff de ta PR, je vais te faire la remarque si je vois un `react-container-component`

2022-12-02 15:07 UTC, lapwil commented on src/containers/Beersliked/__tests__/BeersLiked.spec.js
> +    <BeersLiked/>,
NON NON NON NON NON

2022-12-02 15:07 UTC, lapwil commented on src/containers/TinderContainer.jsx
>        this.props.fetchBeers()
semicolon

2022-12-02 15:07 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +});
ordre alphabétique

2022-12-02 15:07 UTC, lapwil commented on src/sagas/index.js
> +  yield takeLeading(NEXT_BEER, likeSaga.nextBeerSaga)
maintenant que la rootsaga commence à se remplir, tu peux changer pour un seul yield

2022-12-02 15:07 UTC, lapwil commented on src/utils/testTools/initValues.js
> +    "photo_link": "https://img.saveur-biere.com/img/p/82-14662-thickbox_sb3.jpg"
indentation

2022-12-02 15:07 UTC, lapwil commented on src/utils/testTools/setupRenderTest.js
> +;
à mettre à la ligne 13

2022-12-02 15:07 UTC, lapwil commented on src/utils/testTools/customeMethodRTL.js
> +}
pourquoi du coup ?

tu n'as pas besoin de tout ça

2022-12-05 08:49 UTC, lapwil requested changes

2022-12-05 08:49 UTC, lapwil commented on src/containers/Beersliked/Beersliked.jsx
> +    <div>
Tu as mieux à utiliser que div quand une div est pas modifiée

2022-12-05 08:49 UTC, lapwil commented on src/containers/Beersliked/Beersliked.jsx
> +export default connect(
Quelle est la différence entre un component et un container ?

2022-12-05 08:49 UTC, lapwil commented on src/containers/Beersliked/__tests__/BeersLiked.spec.js
> +      beers = { initListBeers }
Pas d'espace dans l'html ou le jsx

2022-12-05 08:49 UTC, lapwil commented on src/containers/Beersliked/__tests__/BeersLiked.spec.js
> +      beers = { initListBeers }
Idem

2022-12-05 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +    const like = () => {
Rien a faire dans le render mets dans la classe

2022-12-05 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +    const dislike = () => {
Idem

2022-12-05 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +      this.props.addLike(beerId);
Quitte à décomposer props fais le pour ça aussi

2022-12-05 08:49 UTC, lapwil commented on src/containers/Beersliked/__tests__/BeersLiked.spec.js
> +import React from "react";
c'est un fichier de test de component contenant du jsx, le nom du fichier est pas correct (je l'avais pas remarqué avant donc fais-le sur tes fichiers de tests de component)

2022-12-05 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +  session: state.settings.session,
à ranger

2022-12-05 08:49 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +  setCurrentBeerIndex: (newCurrentIndex) => dispatch(actions.setCurrentBeerIndex(newCurrentIndex)),
à ranger

2022-12-05 08:49 UTC, lapwil commented on src/reducers/beers.js
> +
newline en trop

2022-12-05 08:49 UTC, lapwil commented on src/reducers/likesReducer.js
> +          data: [...state.data, action.beerId]
mauvaise indentation + virgule manquante

2022-12-05 08:49 UTC, lapwil commented on src/reducers/beers.js
>        return {
attention tu écrases le reste du state ici

2022-12-05 08:49 UTC, lapwil commented on src/sagas/addBeerLikeSaga.js
> +  yield put(setCurrentBeerIndex(currentIndex + 1));
tu pourrais créer une nouvelle action pour incrémenter l'index pour ici et nextbeersaga

2022-12-05 08:49 UTC, lapwil commented on src/utils/getInfoBeer.js
> +  return listBeers.find(beerElem => beerElem.id == beerId);
jamais de `==`

2022-12-05 08:49 UTC, lapwil commented on src/utils/testTools/customeMethodRTL.js
> +const renderWithProviders = ({children}) => (
pour la décomposition, on a des espaces entre les `{}` et ce qu'il y a dedans

2022-12-05 08:49 UTC, lapwil commented on src/utils/testTools/initValues.js
> +export const initListBeers = [
pour tous tes objets ici, tu n'es pas en json, donc les clé n'ont pas à avoir de `"` 

manque des `,` après chaque photo_link

2022-12-05 08:49 UTC, lapwil commented on src/utils/testTools/initValues.js
> +  beer: firstBeer
`,` manquante

2022-12-05 08:49 UTC, lapwil commented on src/utils/testTools/setupRenderTest.js
> +export const setupStore = preloadedState => {
syntaxe à revoir

2022-12-05 09:01 UTC, Mickalu commented on src/containers/Beersliked/Beersliked.jsx
> +export default connect(
Un container est ce qui est relier au store et où on va retrouver la logique des datas qui sont dans le store 
Le component lui est le rendu de ces datas 

Donc ici pas besoin de mettre de connect dans le Beersliked car son container le fait déjà et le changer de place

2022-12-05 11:32 UTC, lapwil requested changes

2022-12-05 11:32 UTC, lapwil commented on src/actions/index.js
> +});
si c'est de l'incrémentation, pas besoin de lui donner l'index, tu y auras déjà accès depuis le state, tout l'intérêt de cet action était de ne pas avoir à select l'index pour l'envoyer au reducer et simplifier tes sagas

2022-12-05 11:32 UTC, lapwil commented on src/utils/testTools/initValues.js
> +};
comme au dessus

2022-12-05 11:32 UTC, lapwil commented on src/components/Beersliked/Beersliked.jsx
> +  const { beers, likes } = props;
ici tu peux utiliser une autre syntaxe pour avoir ta décomposition ligne 7, et du coup avoir la syntaxe ES6 avec des parenthèses

2022-12-05 11:32 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +    };
semi-colon en trop

2022-12-05 11:32 UTC, lapwil commented on src/containers/TinderContainer.jsx
> +    };
semi-colon en trop

2022-12-05 11:32 UTC, lapwil commented on src/containers/__tests__/BeersContainer.test.jsx
> +      beers={ initListBeers }
presque

`attribute={injection}`

2022-12-05 11:32 UTC, lapwil commented on src/containers/__tests__/BeersContainer.test.jsx
> +  render( <BeersLikedContainer.WrappedComponent
mets le à la ligne plutôt comme le test au dessus

2022-12-05 11:32 UTC, lapwil commented on src/containers/__tests__/TindexContainer.spec.jsx
> +    beers={initListBeers}
indentation

2022-12-05 11:32 UTC, lapwil commented on src/reducers/likesReducer.js
> +const likes = (state = { data: [] } , action) => {
une bonne pratique à adopter est de variabiliser l'initial state, ici il n'y a qu'une ligne mais pour un state plus gros mieux vaut que ce soit en dehors

2022-12-05 11:32 UTC, lapwil commented on src/reducers/beer.js
> +    case INCREMENT_INDEX_BEER:
le current beer index n'est plus utilisé ?

attention tu écrases le reste de ton state là.

2022-12-05 11:32 UTC, lapwil commented on src/sagas/startSessionSaga.js
> +  };
semi-colon en trop

2022-12-05 11:32 UTC, lapwil commented on src/utils/getInfoBeer.js
> +  return listBeers.find(beerElem => beerElem.id === beerId);
tu n'as pas d'erreur ici ?

2022-12-05 12:35 UTC, Mickalu commented on src/reducers/beer.js
> +    case INCREMENT_INDEX_BEER:
Non parce que maintenant j'increment directement l'index avec la méthode d"incrémentation mais ce n"est peut-être pas assez lisible

2022-12-05 13:10 UTC, Mickalu commented on src/utils/getInfoBeer.js
> +  return listBeers.find(beerElem => beerElem.id === beerId);
Non j'en ai pas et ça affiche ce que je veux mais il doit en avoir une si tu me le demande ou quelque chose de pas claire

2022-12-05 13:15 UTC, Mickalu commented on src/utils/getInfoBeer.js
> +  return listBeers.find(beerElem => beerElem.id === beerId);
Je l'utilise lors du map pour afficher le titre de chaque bière lors du map

2022-12-05 13:23 UTC, lapwil requested changes
encore quelques changements à faire

d'ailleurs certains retours n'ont pas été traités, vérifies bien dans files les retours qui y sont

2022-12-05 13:23 UTC, lapwil commented on src/reducers/beer.js
> +    case INCREMENT_INDEX_BEER:
okok dans ce cas tu peux retirer les call à CURRENT_BEER_INDEX et setCurrentBeerIndex

2022-12-05 13:23 UTC, lapwil commented on src/utils/getInfoBeer.js
> +  return listBeers.find(beerElem => beerElem.id === beerId);
okok j'ai regardé et oui tu push dans like des string d'id donc ça passe

2022-12-05 13:23 UTC, lapwil commented on src/components/Beersliked/Beersliked.jsx
> +    <div>
du coup maintenant tu peux utiliser l'autre syntaxe ES6 ici

et on a toujours <div> au lieu d'un autre tag React

2022-12-05 13:23 UTC, lapwil commented on src/components/Beersliked/Beersliked.jsx
> +        };
semi colon en trop

2022-12-05 14:38 UTC, lapwil approved these changes

2022-12-05 14:53 UTC, merged